sudo: required
dist: trusty
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=armhf
    - ARCH=armv7
    - ARCH=aarch64
install:
  - sudo ./alpine-chroot-install
script:
  - /alpine/enter-chroot uname -a
  - /alpine/enter-chroot env
  - /alpine/enter-chroot -u $USER env
  - sudo /alpine/enter-chroot -u $USER env
  - apk add bitcoin-cli
  - apk add build-base
  - bpath="$(which bitcoin-cli)"
  - file $bpath
