sudo: required
dist: trusty
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=armhf
    - ARCH=armv7
    - ARCH=aarch64
install:
  - sudo ./alpine-chroot-install -a $ARCH -p build-base -p bitcoin-cli
script:
  - /alpine/enter-chroot uname -a
  - /alpine/enter-chroot env
  - /alpine/enter-chroot -u $USER env
  - sudo /alpine/enter-chroot -u $USER env
  - /alpine/enter-chroot -u $USER file /usr/bin/bitcoin-cli
